# Generated by Django 5.0.1 on 2024-02-08 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва речі')),
                ('description', models.TextField(max_length=100, verbose_name='Опис речі')),
                ('category', models.CharField(choices=[('electronic', 'Електроніка'), ('clothing', 'Одяг'), ('shoes', 'Взуття'), ('accessories', 'Аксесуари'), ('toys', 'Іграшки'), ('furniture', 'Меблі'), ('repair', 'Ремонт'), ('auto', 'Авто'), ('animals', 'Тварини'), ('hobby', 'Хоббі і відпочинок'), ('sport', 'Спорт'), ('other', 'Інше')], max_length=20, verbose_name='Категорія')),
                ('exchange_category', models.CharField(choices=[('electronic', 'Електроніка'), ('clothing', 'Одяг'), ('shoes', 'Взуття'), ('accessories', 'Аксесуари'), ('toys', 'Іграшки'), ('furniture', 'Меблі'), ('repair', 'Ремонт'), ('auto', 'Авто'), ('animals', 'Тварини'), ('hobby', 'Хоббі і відпочинок'), ('sport', 'Спорт'), ('other', 'Інше')], max_length=20, verbose_name='Категорія для обміну')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Річ',
                'verbose_name_plural': 'Речі',
            },
        ),
    ]
