# Generated by Django 5.0.1 on 2024-02-10 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_appp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('item_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_requests', to='exchange_appp.item')),
                ('item_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_requests', to='exchange_appp.item')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запит на обмін',
                'verbose_name_plural': 'Запити на обмін',
            },
        ),
    ]
